--Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

--Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';



--Explore All Countries our customer come from.
SELECT DISTINCT country FROM gold.dim_customers;

--Eeplore All categories "The major Division"
SELECT DISTINCT	category, subcategory, product_name FROM gold.dim_products
ORDER BY 1, 2, 3;



-- Find the date of first and last order
-- How many years of sales are available
SELECT 
MIN(order_date) as first_date,
MAX(order_date) as last_date,
DATEDIFF(year, MIN(order_date), MAX(order_date)) as order_range_months
FROM gold.fact_sales

--Find the youngest and oldest customer
SELECT 
MIN(birthdate) as oldest_cutomer,
DATEDIFF(year, MIN(birthdate), GETDATE()) as oldest_age,
MAX(birthdate) as youngest_customer,
DATEDIFF(year, MAX(birthdate), GETDATE()) as youngest_age

FROM gold.dim_customers
 


 -- Find the Total Sales
  SELECT SUM(sales_amount) as total_sales FROM gold.fact_sales

 -- Find how many items are sold
 SELECT SUM(quantity) as total_quantity FROM gold.fact_sales

 -- Find the average selling price 
 SELECT AVG(price) as avg_price FROM gold.fact_sales

 -- Find the Total number of orders
 SELECT COUNT(order_number) as total_orders FROM gold.fact_sales
 SELECT COUNT(DISTINCT order_number) as total_orders FROM gold.fact_sales

 -- Find the Total number of products
 SELECT COUNT(DISTINCT product_key) as total_products FROM gold.dim_products

 -- Find the Total number of customers
 SELECT COUNT(DISTINCT customer_key) as total_customers FROM gold.dim_customers

 -- Find the Total number of cutomers that has placed an order
 SELECT COUNT(DISTINCT customer_key) as total_customers FROM gold.fact_sales
 

 -- Generate a Report that shows all key metrics of the business

SELECT 'Total sales' as measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. order', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. products', COUNT(DISTINCT product_key) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. customers', COUNT(DISTINCT customer_key) FROM gold.dim_customers
UNION ALL

-- Find total customers by countries
SELECT
country,
COUNT(DISTINCT customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
gender,
COUNT(DISTINCT customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT
category,
COUNT(DISTINCT product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT
category,
AVG(cost) as Avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_cost DESC

-- What is the total revenue generated for each category?
SELECT
p.category,
SUM(f.sales_amount) as toatl_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY toatl_revenue DESC

-- Find total revenue is generated by each customer?
SELECT 
customer_key,
SUM(sales_amount) total_revenue
FROM gold.fact_sales
GROUP BY customer_key
ORDER BY total_revenue DESC

-- What is the distribution of sold itmes across countries?
SELECT 
c.country,
COUNT(f.quantity) as total_sold_items
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

-- Which 5 products generate the highest revenue ?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) as total_sales
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY product_name
ORDER BY total_sales DESC

-- Using WNIDOW FUNCTION (RANK())
SELECT 
*
FROM(
SELECT
p.product_name,
SUM(f.sales_amount) as total_sales,
RANK() OVER(ORDER BY SUM(f.sales_amount) DESC) as rank_products
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY product_name)t
WHERE rank_products <= 5



-- Which 5 products generate the lowest revenue ?
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) as total_sales
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY product_name
ORDER BY total_sales 

-- Using WNIDOW FUNCTION (RANK())
SELECT
*
FROM
(
SELECT 
p.product_name,
SUM(f.sales_amount) as total_sales,
RANK() OVER(ORDER BY SUM(f.sales_amount) ASC) as rank_products
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY product_name)t
WHERE rank_products <= 5



-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_sales
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_sales DESC

-- The 3 customers with the fewest orders placed 
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) as total_orders
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_orders 
